[package]
name = "rusty-hasher"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.1", features = ["derive"] }
sha2 = "0.10"
md5 = "0.7"
sha1 = "0.10"
blake3 = "1.5"
arboard = "3.3"
colored = "2.1"